<a href="https://colab.research.google.com/github/sajeebju/Deep-Learning/blob/main/tensorflowOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
print(tf.constant(3))

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
x = tf.constant(4, shape = (1,1), dtype= tf.float32)

In [ ]:
x = tf.constant([[1,2,3], [4,5,6]])

print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
x = tf.zeros((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
x = tf.eye(5)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
x = tf.random.normal((3,3,), mean = 0, stddev = 1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.002498  ,  0.5084861 , -1.1954235 ],
       [-0.08778968, -1.2823145 , -0.33342233],
       [ 0.19100697,  0.5024928 , -0.8879077 ]], dtype=float32)>

In [ ]:
x = tf.random.uniform((1,3), minval = 0, maxval = 1)
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.7068136 , 0.5153552 , 0.99321544]], dtype=float32)>

In [ ]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
x = tf.range(start = 1, limit = 10, delta = 2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [ ]:
x = tf.cast(x, dtype = tf.float64)
x

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

In [ ]:
 x = tf.constant([1,2,3])
 y = tf.constant([9,8,7])

 z = tf.add(x, y)
 print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
import numpy as np

x = np.array([1,2,3])
y = np.array([9,8,7])

z = np.add(x,y)

In [ ]:
z

array([10, 10, 10])

In [ ]:
tf.subtract(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
z = x-y
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4], dtype=int32)>

In [ ]:
z  =tf.divide(x, y)
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [ ]:
z = x/y

In [ ]:
z = tf.multiply(x, y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
z = tf.tensordot(x, y, axes = 1)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
z = tf.reduce_sum(x*y, axis = 0)
z

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [ ]:
z = x **5
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243], dtype=int32)>

In [ ]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

z = tf.matmul(x, y)
z

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.19750705,  0.9386419 ,  0.48587352,  1.6554149 ],
       [-0.51904213, -0.16185665,  0.7704729 ,  0.60052943]],
      dtype=float32)>

In [ ]:
z = x @ y

print(z)

tf.Tensor(
[[ 0.19750705  0.9386419   0.48587352  1.6554149 ]
 [-0.51904213 -0.16185665  0.7704729   0.60052943]], shape=(2, 4), dtype=float32)


In [ ]:
x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [ ]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [ ]:
print(x[:-1])

tf.Tensor([0 1 1 2 3 1 2], shape=(7,), dtype=int32)


In [ ]:
print(x[2::-1])

tf.Tensor([1 1 0], shape=(3,), dtype=int32)


In [ ]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>

In [ ]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2], dtype=int32)>

In [ ]:
x

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3], dtype=int32)>

In [ ]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0], dtype=int32)>

In [ ]:
indices = tf.constant([0, 3])
x_ind = tf.gather(x, indices)
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

In [ ]:
print(x[0, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
print(x[0:2, :])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
x = tf.reshape(x, (3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
x = tf.transpose(x, perm = [1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
